export const commentConstants = {
  GET_COMMENTS_REQUEST: 'GET_COMMENTS_REQUEST',
  GET_COMMENTS_SUCCESS: 'GET_COMMENTS_SUCCESS',
  GET_COMMENTS_FAILURE: 'GET_COMMENTS_FAILURE',

  UPLOAD_COMMENT_REQUEST: 'UPLOAD_COMMENT_REQUEST',
  UPLOAD_COMMENT_SUCCESS: 'UPLOAD_COMMENT_SUCCESS',
  UPLOAD_COMMENT_FAILURE: 'UPLOAD_COMMENT_FAILURE',

  COMMENT_CHANGE: 'COMMENT_CHANGE',

  // GET_PROFILE_REQUEST: 'GET_PROFILE_REQUEST',
  // GET_PROFILE_SUCCESS: 'GET_PROFILE_SUCCESS',
  // GET_PROFILE_FAILURE: 'GET_PROFILE_FAILURE',
};
