export const profileConstants = {
  PROFILE_CHANGE: 'PROFILE_CHANGE',
  PROFILE_IMAGE_CHANGE: 'PROFILE_IMAGE_CHANGE',

  PROFILE_SAVE_REQUEST: 'PROFILE_SAVE_REQUEST',
  PROFILE_SAVE_SUCCESS: 'PROFILE_SAVE_SUCCESS',
  PROFILE_SAVE_FAILURE: 'PROFILE_SAVE_FAILURE',

  GET_PROFILE_REQUEST: 'GET_PROFILE_REQUEST',
  GET_PROFILE_SUCCESS: 'GET_PROFILE_SUCCESS',
  GET_PROFILE_FAILURE: 'GET_PROFILE_FAILURE',
};
