export const postConstants = {
  GET_POSTS_REQUEST: 'GET_POSTS_REQUEST',
  GET_POSTS_SUCCESS: 'GET_POSTS_SUCCESS',
  GET_POSTS_FAILURE: 'GET_POSTS_FAILURE',

  UPLOAD_POST_REQUEST: 'UPLOAD_POST_REQUEST',
  UPLOAD_POST_SUCCESS: 'UPLOAD_POST_SUCCESS',
  UPLOAD_POST_FAILURE: 'UPLOAD_POST_FAILURE',

  // GET_PROFILE_REQUEST: 'GET_PROFILE_REQUEST',
  // GET_PROFILE_SUCCESS: 'GET_PROFILE_SUCCESS',
  // GET_PROFILE_FAILURE: 'GET_PROFILE_FAILURE',
};
